[Variables]
; -- HWiNFO --
HWiNFO-CONFIGPATH=D:\Files\Settings\Caleb\Rainmeter\Skins\illustro Gadgets\@Resources\Settings\HWiNFOConfig.inc

; -- Visual Properties --
enableLineGraphAntialiasing=0
dEnableLineGraphAntialiasing=0

colorPrimary=250,250,250,200
dColorPrimary=250,250,250,200

colorSecondary=250,250,250,155
dColorSecondary=250,250,250,155

colorAccent=138,210,250,200
dColorAccent=138,210,250,200

colorDim=100,100,100,51
dColorDim=100,100,100,51

colorSeparator=192,192,192,64
dColorSeparator=192,192,192,64

; ---------- ADVANCED ----------

colorButton=#colorPrimary#
dColorButton=#dColorPrimary#

colorGraphBg=#colorDim#
dColorGraphBg=#dColorDim#

alphaButton=200
alphaBar=200
alphaLine=200
alphaPrimary=200
alphaSecondary=155
