[Variables]
; -- General Visual Properties --
hideHistogram=0
hideGraph=0
hideDriveWarnings=1

; -- Drives --
; Hide
hideDiskD=0
hideDiskE=0
hideDiskF=0
hideDiskG=0
hideDiskH=0
hideDiskI=0
hideDiskJ=0
hideDiskK=0
hideDiskL=0

; Colors
colorDisk1=107,238,98
colorDisk2=255,246,42
colorDisk3=250,158,0
colorDisk4=236,28,70
colorDisk5=199,36,199
colorDisk6=145,70,232
colorDisk7=42,112,250
colorDisk8=43,224,224
colorDisk9=121,182,62
colorDisk10=204,255,0
colorDiskCapacityWarn=220,200,0
colorDiskCapacityFull=200,0,0