[Variables]
; -- General visual properties --
hideGpuName=0
hideShaderClock=0
hideMemController=0
hideCoreVoltage=1
hideLineGraph=0

; Dual GPU Meter
graphType=3

; -- Colors --
sColorTotalUsage=255,246,42,200
sColorMemoryUsage=107,198,250,200
sColorFanUsage=107,238,98,200
sColorMemController=250,158,0,200

; ----- Defaults -----

dHideShaderClock=0
dHideMemController=0
dHideCoreVoltage=1
dHideLineGraph=0

dGraphType=3
dHideGpuName=0

dColorTotalUsage=255,246,42,200
dColorMemoryUsage=107,198,250,200
dColorFanUsage=107,238,98,200
dColorMemController=250,158,0,200
dColorCoreVoltage=236,28,70,200
