[Variables]
; -- General visual properties --
hideMemController=0
hideCoreVoltage=0
hideLineGraph=0

; -- Colors --
sColorTotalUsage=255,246,42
sColorMemoryUsage=107,198,250
sColorFanUsage=107,238,98
sColorMemController=250,158,0

; ----- Defaults -----

dHideMemController=0
dHideCoreVoltage=0
dHideLineGraph=0

dColorTotalUsage=255,246,42
dColorMemoryUsage=107,198,250
dColorFanUsage=107,238,98
dColorMemController=250,158,0
dColorCoreVoltage=236,28,70
