[Variables]
;
; CPU 0
;
; sensor ID and instance
HWiNFO-CPU0-SensorId=0xf0000300
HWiNFO-CPU0-SensorInstance=0x0
; entry IDs
; CPU usage (percent)
HWiNFO-CPU0-Usage=0x7000009
; core 0 clock frequency (MHz)
HWiNFO-CPU0-Core0Clock=0x6000000
; core 1 clock frequency (MHz)
HWiNFO-CPU0-Core1Clock=0x6000001
; core 2 clock frequency (MHz)
HWiNFO-CPU0-Core2Clock=0x6000002
; core 3 clock frequency (MHz)
HWiNFO-CPU0-Core3Clock=0x6000003
; core 4 clock frequency (MHz)
HWiNFO-CPU0-Core4Clock=0x6000004
; core 5 clock frequency (MHz)
HWiNFO-CPU0-Core5Clock=0x6000005
; core 6 clock frequency (MHz)
HWiNFO-CPU0-Core6Clock=0x6000006
; core 7 clock frequency (MHz)
HWiNFO-CPU0-Core7Clock=0x6000007
; core 0 voltage (volts)
HWiNFO-CPU0-Core0Volts=0x2000000
; core 1 voltage (volts)
HWiNFO-CPU0-Core1Volts=0x2000001
; core 2 voltage (volts)
HWiNFO-CPU0-Core2Volts=0x2000002
; core 3 voltage (volts)
HWiNFO-CPU0-Core3Volts=0x2000003
; core 4 voltage (volts)
HWiNFO-CPU0-Core4Volts=0x2000004
; core 5 voltage (volts)
HWiNFO-CPU0-Core5Volts=0x2000005
; core 6 voltage (volts)
HWiNFO-CPU0-Core6Volts=0x2000006
; core 7 voltage (volts)
HWiNFO-CPU0-Core7Volts=0x2000007

;
; CPU 0 DTS
;
; sensor ID and instance
HWiNFO-CPU0-DTS-SensorId=0xf0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
; entry IDs
; core 0 temperature (degrees)
HWiNFO-CPU0-DTS-Core0Temp=0x1000000
; core 1 temperature (degrees)
HWiNFO-CPU0-DTS-Core1Temp=0x1000001
; core 2 temperature (degrees)
HWiNFO-CPU0-DTS-Core2Temp=0x1000002
; core 3 temperature (degrees)
HWiNFO-CPU0-DTS-Core3Temp=0x1000003
; core 4 temperature (degrees)
HWiNFO-CPU0-DTS-Core4Temp=0x1000004
; core 5 temperature (degrees)
HWiNFO-CPU0-DTS-Core5Temp=0x1000005
; core 6 temperature (degrees)
HWiNFO-CPU0-DTS-Core6Temp=0x1000006
; core 7 temperature (degrees)
HWiNFO-CPU0-DTS-Core7Temp=0x1000007
; maximum current core temperature (degrees)
HWiNFO-CPU0-DTS-CoreMax=0x100007f

;
; Motherboard
;
; sensor ID and instance
HWiNFO-MOBO-SensorId=0xf7067760
HWiNFO-MOBO-SensorInstance=0x0
; entry IDs
; CPU fan speed (RPM)
HWiNFO-MOBO-CPUFan=0x3000000
; GPU fan speed (RPM)
HWiNFO-MOBO-GPUFan=0x3000001

;
; GPU 0
;
; sensor ID and instance
HWiNFO-GPU0-SensorId=0xe0002000
HWiNFO-GPU0-SensorInstance=0x14
; entry IDs
; GPU core clock frequency (MHz)
HWiNFO-GPU0-Clock=0x6000000
; GPU temperature (degrees)
HWiNFO-GPU0-Temp=0x1000000
; GPU load (percent)
HWiNFO-GPU0-CoreLoad=0x7000000
; GPU memory clock frequency (MHz)
HWiNFO-GPU0-MemoryClock=0x6000004
; GPU memory usage (percent)
HWiNFO-GPU0-MemoryUsage=0x7000008
; GPU memory allocated (MB)
HWiNFO-GPU0-MemoryAlloc=0x800003c
; GPU fan speed (RPM)
HWiNFO-GPU0-FanSpeed=0x3000000
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU0-FanUsage=0x8000000
; GPU memory controller usage
HWiNFO-GPU0-MemController=0x7000001
; GPU core voltage (volts)
HWiNFO-GPU0-CoreVoltage=0x2000000

;
; GPU 1
;
; sensor ID and instance
HWiNFO-GPU1-SensorId=0xe0002000
HWiNFO-GPU1-SensorInstance=0x0
; entry IDs
; GPU core clock frequency (MHz)
HWiNFO-GPU1-Clock=0x6000000
; GPU temperature (degrees)
HWiNFO-GPU1-Temp=0x1000000
; GPU load (percent)
HWiNFO-GPU1-CoreLoad=0x7000000
; GPU memory clock frequency (MHz)
HWiNFO-GPU1-MemoryClock=0x6000004
; GPU memory usage (percent)
HWiNFO-GPU1-MemoryUsage=0x7000008
; GPU memory allocated (MB)
HWiNFO-GPU1-MemoryAlloc=0x800003c
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU1-FanSpeed=0x8000000
; GPU core voltage (volts)
HWiNFO-GPU1-CoreVoltage=0x2000000