[Variables]
; -- General visual properties --
hideRefresh=0
hideLineGraph=0

; -- Colors --
sColorHyperlink=236,28,70
sColorUpload=107,238,98
sColorDownload=255,246,42

; -- Interfaces --
;
; Set the interface identifiers to match your system.  If your machine does not have have an adapter
; of the specified type or to turn off monitoring, use 0 as the identifier.  Set all interfaces to 0
; to have rainmeter report on all adapters, but if you have any virtualized interfaces active, the
; NetIn/NetOut/NetTotal measures will be incorrect.  See http://docs.rainmeter.net/tips/network-skin
; for an explanation and details on how to find your network interface indentifiers.  Use the
; Settings gadget to configure these values or enter them here.  Unless you have a machine with
; multiple network cards installed (i.e., like a server), you should only have one ACTIVE PHYSICAL
; network interface of each type, all other reported interfaces should be virtual or disconnected.
;
interfaceBroadband=0
interfaceEthernet=0
interfaceWireless=0