[Variables]
; ## GENERAL ##
version="0.7.0-d2"
versionAbsolute=0702
updatedDate="04 October 2015"
RainRGB=#@#Addons/RainRGB/RainRGB4.exe

; ## FONT FACES AND SIZES ##
fontName=Trebuchet MS
fontName2=Segoe UI
fontSize=8
fontSize2=9
fontSize3=10
titleSize=10

; ## POSITIONING ##
bodyStartY=37
barTextYOffset=13
barHeight=1
rowYOffset=15
scale=1
graphWidth=190
graphHeight=41
textXMarginLeft=9

; ## COLORS AND GHOSTING ##
colorText=255,255,255,#opacityNormal#
colorTextGhosted=225,225,225,#opacityGhosted#
colorTextNoAlpha=255,255,255
colorTextLink=138,210,255
colorSeparator=192,192,192,64
colorSolidBar=105,105,105,#opacityGhosted#
colorGraphBG=160,160,160,#opacityGraph#

opacityNormal=200
opacityGhosted=150
opacityGraph=40

; DEGREES SYMBOL: °
