[Variables]
; -- CPU Cores --
cpuCores=4
threadsPerCore=2

; Hide
hideCore2=0
hideCore3=0
hideCore4=0
hideCore5=1
hideCore6=1
hideCore7=1
hideCore8=1
hideCore9=1
hideCore10=1
hideCore11=1
hideCore12=1
hideCore13=1
hideCore14=1
hideCore15=1
hideCore16=1

; -- HWiNFO --
isHWiNFOInUse=0

; -- Positioning --
bgWidth=210
; bgHeight is defined in the [MeasureBgHeightCalc] measure in AllCpuMeter.ini
bgHeight=
bgCenterX=(#bgWidth# / 2)
generalXMarginRight=(#bgWidth# - 10)
graphWidth=(#bgWidth# - #generalXMarginLeft# - (#bgWidth# - #generalXMarginRight# + 1))

; -- Colors (Dynamic) --
gColorCore1=0,0,0
gColorCore2=0,0,0
gColorCore3=0,0,0
gColorCore4=0,0,0
gColorCore5=0,0,0
gColorCore6=0,0,0
gColorCore7=0,0,0
gColorCore8=0,0,0
gColorCore9=0,0,0
gColorCore10=0,0,0
gColorCore11=0,0,0
gColorCore12=0,0,0
gColorCore13=0,0,0
gColorCore14=0,0,0
gColorCore15=0,0,0
gColorCore16=0,0,0
gColorRam=0,0,0,0
gColorPage=0,0,0
gColorAvgCpu=0,0,0
gColorFan=0,0,0

gAlphaCore1=0
gAlphaCore2=0
gAlphaCore3=0
gAlphaCore4=0
gAlphaCore5=0
gAlphaCore6=0
gAlphaCore7=0
gAlphaCore8=0
gAlphaCore9=0
gAlphaCore10=0
gAlphaCore11=0
gAlphaCore12=0
gAlphaCore13=0
gAlphaCore14=0
gAlphaCore15=0
gAlphaCore16=0
gAlphaRam=0,0
gAlphaPage=0
gAlphaAvgCpu=0
gAlphaFan=0

; -- Dynamic Variables --
textRAMUsed=""
textRAMTotal=""
textPageUsed=""
textPageTotal=""
