[Variables]
; -- Version --
version="0.9.0"

; -- Addons --
rainRGB=#@#Addons\RainRGB\RainRGB4.exe
rainFile=#@#Addons\RainFile\RainFile.exe
hwinfoSmv=#@#Addons\HWiNFO\HWiNFOSharedMemoryViewer.exe

; -- Scripts --
fixedPrecisionFormatScript=#@#Scripts\FixedPrecisionFormat.lua
settingsScript=#@#Scripts\Settings.lua
graphColorConfigScript=#@#Scripts\GraphColorConfig.lua

; -- General Visual Properties --
generalXMarginLeft=9

bodyStartY=37
rowYOffset=16
barTextYOffset=13
nextRowBelowLineOffset=(#rowYOffset# - #barTextYOffset#)
barHeight=1

graphHeight=41

scale=1

colorSeparator=192,192,192,64

; -- Font Properties --
fontFace=Trebuchet MS
fontFace2=Segoe UI

fontSize=8
fontSize2=9
fontSize3=12
titleSize=10

; DEGREES SYMBOL: °