[Variables]
; -- Version --
version="0.7.0-d.6"
versionAbsolute=0706

; -- Addons --
rainRGB=#@#Addons\RainRGB\RainRGB4.exe
rainFile=#@#Addons\RainFile\RainFile.exe

; -- Scripts --
fixedPrecisionFormatScript=#@#Scripts\FixedPrecisionFormat.lua

; -- General Visual Properties --
generalXMarginLeft=9

bodyStartY=37
rowYOffset=16
barTextYOffset=13
nextRowBelowLineOffset=(#rowYOffset# - #barTextYOffset#)
barHeight=1

graphHeight=41

scale=1

; -- Font Properties --
fontFace=Trebuchet MS
fontFace2=Segoe UI

fontSize=8
fontSize2=9
fontSize3=12
titleSize=10

; DEGREES SYMBOL: °