[Variables]
; -- General Skin Pack Info --
version="0.7.0-d.4"
versionAbsolute=0704
updatedDate="25 October 2015"
platform="Rainmeter 3.3 (r2468)"
license="Creative Commons BY-NC-SA 3.0"
author="iamanai"

; -- Addons --
rainRGB=#@#Addons\RainRGB\RainRGB4.exe
rainFile=#@#Addons\RainFile\RainFile.exe

; -- Scripts --
fixedPrecisionFormatScript=#@#Scripts\FixedPrecisionFormat.lua

; -- General Visual Properties --
generalXMarginLeft=9

generalOpacity=200
ghostedOpacity=150

bodyStartY=37
rowYOffset=16

barTextYOffset=13
barHeight=1
barSolidColor=105,105,105,#ghostedOpacity#

graphHeight=41
graphBgColor=160,160,160
graphBgColorAlt=80,80,80
graphOpacity=40

separatorBarColor=192,192,192
separatorBarOpacity=64

scale=1

; -- Font Properties --
fontFace=Trebuchet MS
fontFace2=Segoe UI

fontSize=8
fontSize2=9
titleSize=10

fontColor=255,255,255
fontColorLink=138,210,255

; DEGREES SYMBOL: °