[Variables]
bgWidth=480
bgHeight=470
pageName=AboutScreen

; -- Visual Properties --
generalXMarginRight=(#bgWidth# - 12)

panelWidth=(#bgWidth# - 40)
panelCenterX=((#panelWidth# / 2) + 35)
separatorBarX=#panelCenterX#

checkboxColor=255,255,255,#generalOpacity#
navBarButtonColor=255,255,255,#generalOpacity#

; Text Input
colorInputTextBackground=255,255,255,255
colorInputTextFont=0,0,0
alphaInputTextFont=255
