[Variables]
bgWidth=600
bgHeight=450
pageName=appearance

; -- Visual Properties --
generalXMarginRight=(#bgWidth# - 12)

panelWidth=(#bgWidth# - 40)
panelCenterX=((#panelWidth# / 2) + (#navMenuSeparatorX# / 2) + #generalXMarginLeft#)

checkboxColor=255,255,255,#generalOpacity#
navBarButtonColor=255,255,255,#generalOpacity#

navMenuSeparatorX=150
panelContentMarginLeftX=(#navMenuSeparatorX# + 10)

; Text Input
colorInputTextBackground=0,0,0,255
colorInputTextFont=#colorSecondary#
